version: '3.7'

services:
  init:
    image: bash
    container_name: init
    privileged: true
    user: root
    volumes:
      - ./init.sh:/mnt/init.sh
    command: [ "sh", "-e", "/mnt/init.sh" ]
    networks:
      - localNet
  sonarqube:
    image: sonarqube:9.3-community
    container_name: sonarqube
    ports:
      - 19000:9000
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgresql/sonar
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: 123456
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions
    depends_on:
      - postgresql
    links:
      - postgresql
    networks:
      - localNet
  postgresql:
    image: bitnami/postgresql:11
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRESQL_DATABASE: sonar
    ports:
      - 0.0.0.0:5432:5432
    volumes:
      - ./postgresql_data:/bitnami/postgresql
    networks:
      - localNet
networks:
  localNet:
    external: true